yaml
workflows:
  ios-workflow:
    name: iOS LiDAR Scanner Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: codemagic_app_store_connect
    environment:
      xcode: 15.1
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.yourcompany.lidarscanner  # Change this to your preferred ID
    scripts:
      - name: Create Xcode project structure
        script: |
          # Create a proper Xcode project structure
          mkdir -p LiDARRoomScanner.xcodeproj
          mkdir -p LiDARRoomScanner
          
          # Move all Swift files to the project directory
          find . -name "*.swift" -not -path "./LiDARRoomScanner/*" -exec mv {} LiDARRoomScanner/ \;
          
          echo "Project structure created successfully"
          
      - name: Generate project.pbxproj
        script: |
          cat > LiDARRoomScanner.xcodeproj/project.pbxproj << 'EOF'
          // !$*UTF8*$!
          {
            archiveVersion = 1;
            classes = {};
            objectVersion = 56;
            objects = {
              D2A5F2001F8E86230040F4C2 /* Project object */ = {
                isa = PBXProject;
                attributes = {
                  BuildIndependentTargetsInParallel = 1;
                  LastSwiftUpdateCheck = 1500;
                  LastUpgradeCheck = 1500;
                  TargetAttributes = {
                    D2A5F2071F8E86230040F4C2 = {
                      CreatedOnToolsVersion = 15.0;
                      DevelopmentTeam = "$(DEVELOPMENT_TEAM)";
                    };
                  };
                };
                buildConfigurationList = D2A5F2031F8E86230040F4C2;
                compatibilityVersion = "Xcode 14.0";
                developmentRegion = en;
                hasScannedForEncodings = 0;
                knownRegions = (en, Base);
                mainGroup = D2A5F1FF1F8E86230040F4C2;
                productRefGroup = D2A5F2091F8E86230040F4C2;
                projectDirPath = "";
                projectRoot = "";
                targets = (D2A5F2071F8E86230040F4C2);
              };
              D2A5F21E1F8E86230040F4C2 /* Release */ = {
                isa = XCBuildConfiguration;
                buildSettings = {
                  ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
                  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME = AccentColor;
                  CODE_SIGN_STYLE = Automatic;
                  CURRENT_PROJECT_VERSION = 1;
                  DEVELOPMENT_ASSET_PATHS = "";
                  DEVELOPMENT_TEAM = "$(DEVELOPMENT_TEAM)";
                  ENABLE_PREVIEWS = YES;
                  GENERATE_INFOPLIST_FILE = YES;
                  INFOPLIST_KEY_NSCameraUsageDescription = "Camera access is required for LiDAR room scanning and 3D reconstruction.";
                  INFOPLIST_KEY_NSLocationWhenInUseUsageDescription = "Location is used to enhance AR tracking accuracy during room scanning.";
                  INFOPLIST_KEY_UIApplicationSceneManifest_Generation = YES;
                  INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents = YES;
                  INFOPLIST_KEY_UILaunchScreen_Generation = YES;
                  INFOPLIST_KEY_UISupportedInterfaceOrientations = "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight";
                  INFOPLIST_KEY_UIRequiredDeviceCapabilities = "arkit lidar arm64";
                  LD_RUNPATH_SEARCH_PATHS = ("$(inherited)", "@executable_path/Frameworks");
                  MARKETING_VERSION = 1.0;
                  PRODUCT_BUNDLE_IDENTIFIER = "com.yourcompany.lidarscanner";  // Must match App Store Connect
                  PRODUCT_NAME = "$(TARGET_NAME)";
                  SWIFT_EMIT_LOC_STRINGS = YES;
                  SWIFT_VERSION = 5.0;
                  TARGETED_DEVICE_FAMILY = "1,2";
                };
                name = Release;
              };
            };
            rootObject = D2A5F2001F8E86230040F4C2;
          }
          EOF
          
      - name: Build iOS app
        script: |
          echo "Building LiDAR Room Scanner..."
          
          xcodebuild -project LiDARRoomScanner.xcodeproj \
            -scheme LiDARRoomScanner \
            -configuration Release \
            -destination generic/platform=iOS \
            -archivePath build/LiDARRoomScanner.xcarchive \
            archive \
            CODE_SIGN_STYLE=Automatic \
            DEVELOPMENT_TEAM="$APP_STORE_CONNECT_ISSUER_ID" \
            PRODUCT_BUNDLE_IDENTIFIER="com.yourcompany.lidarscanner" \
            IPHONEOS_DEPLOYMENT_TARGET=15.0 \
            MARKETING_VERSION=1.0 \
            CURRENT_PROJECT_VERSION=1
          
          # Export IPA
          xcodebuild -exportArchive \
            -archivePath build/LiDARRoomScanner.xcarchive \
            -exportPath build \
            -exportOptionsPlist ExportOptions.plist
    artifacts:
      - build/*.ipa
      - build/LiDARRoomScanner.xcarchive
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: false