yaml
workflows:
  ios-workflow:
    name: iOS LiDAR Scanner Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: codemagic_app_store_connect
    environment:
      xcode: 15.1
      ios_signing:
        distribution_type: development  # Change to development for testing
        bundle_identifier: com.apple.sample.lidarscanner
    scripts:
      - name: Build for development testing
        script: |
          echo "Building for development testing..."
          
          # Create basic Xcode project
          mkdir -p LiDARRoomScanner.xcodeproj
          mkdir -p LiDARRoomScanner
          
          # Move Swift files
          find . -name "*.swift" -not -path "./LiDARRoomScanner/*" -exec mv {} LiDARRoomScanner/ \;
          
          # Build for development
          xcodebuild -project LiDARRoomScanner.xcodeproj \
            -scheme LiDARRoomScanner \
            -configuration Debug \
            -destination generic/platform=iOS \
            -archivePath build/LiDARRoomScanner.xcarchive \
            archive \
            CODE_SIGN_STYLE=Automatic \
            DEVELOPMENT_TEAM="$APP_STORE_CONNECT_ISSUER_ID" \
            PRODUCT_BUNDLE_IDENTIFIER="com.apple.sample.lidarscanner"
    artifacts:
      - build/LiDARRoomScanner.xcarchive